### PR TITLE
Refactoring, use MAC address as ID

### PR DESCRIPTION
**Pull request by juzsal**
- Refactored out main read loop into new Detector class
- Store general state information (number of events, sequence number etc.) in Detector class
- Store current status of each sensor in new Sensors class
- Simplified Event class - instances of Event are now created when it is time to send an event and populated with the latest sensor values
- Use the MAC address of the first known network interface as the detector ID and send it with each event packet
- Quietened down pika logging

### CODE REVIEW

**Comment by juzsal** [comment]
Note that I used the `netifaces` library to get the MAC address, so you'll need to install it.

**Comment by quixoft** [comment]
Ok, today I am having guests for bbq, tomorrow I will pull it and test it.

**Comment by juzsal** [comment]
Ok, going to merge then.

**Comment by quixoft** [comment]
Yes I will test it on two versions of Linux, it will also be interesting to see what it does on a Windows virtual machine.

**Pull request merged**
