### PR TITLE
Split cosmicpi-daq.py into multiple files, one class per file

### PR DESCRIPTION
**Pull request by juzsal**

### CODE REVIEW

**Comment by quixoft** [comment]
Good now they will correspond with what you have at the server and should be shareable between the two, keyboard for example. How can you arrange sharing across Git archives

**Comment by juzsal** [comment]
I think you can use a syntax like `git://github.com/CosmicPi/some-shared-repo.git#egg=shared-package` to add a dependency to a python package hosted on github from inside a setup.py or a requirements.txt. Something we should definitely think about, yes

**Comment by quixoft** [comment]
Can't you use symbolic links. Certainly you can have sym links within an
archive. As long as the relationship between two archives is fixed within
say, the same directory, then add long as both are instantiated in the same
way it should work. I did this on the past. I had one Git repo that
contained two other got repos that had symbolic links between them.

On Wed, May 11, 2016, 21:41 Justin Lewis Salmon notifications@github.com
wrote:

> Merged #9 https://github.com/CosmicPi/cosmicpi-daq/pull/9.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/9#event-657680870
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by quixoft** [comment]
Shit spell checker, basically one Git repo contains other Git repos that
link between themselves

On Wed, May 11, 2016, 21:48 Julian Lewis lewis.julian@gmail.com wrote:

> Can't you use symbolic links. Certainly you can have sym links within an
> archive. As long as the relationship between two archives is fixed within
> say, the same directory, then add long as both are instantiated in the same
> way it should work. I did this on the past. I had one Git repo that
> contained two other got repos that had symbolic links between them.
> 
> On Wed, May 11, 2016, 21:41 Justin Lewis Salmon notifications@github.com
> wrote:
> 
> > Merged #9 https://github.com/CosmicPi/cosmicpi-daq/pull/9.
> > 
> > —
> > You are receiving this because you commented.
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/CosmicPi/cosmicpi-daq/pull/9#event-657680870
> > 
> > ## 
> 
> Julian Lewis
> Mobile: +33646447515
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Pull request merged**
