### PR TITLE
Use the print function rather than the print statement to be forward-compatible

### PR DESCRIPTION
**Pull request by juzsal**
Python 3 doesn't have a print statement, only a builtin function. See [here](https://docs.python.org/2/library/functions.html#print)

### CODE REVIEW

**Comment by quixoft** [comment]
Loads of people are still on 2.7, be careful. What version is on the pi by default. Ubuntu 14.04 is still on 2.7

**Comment by juzsal** [comment]
Note at the top of the file:

``` python
from __future__ import print_function
```

See [here](http://stackoverflow.com/questions/7075082/what-is-future-in-python-used-for-and-how-when-to-use-it-and-how-it-works) about how `__future__` works

**Comment by quixoft** [comment]
Ok, I hadn't used future before, if we include that we should be sure to test it on both versions. Just in case

**Comment by juzsal** [comment]
It works in all versions greater than 2.6.0, it's universally used

**Comment by juzsal** [comment]
OK to merge?

**Comment by quixoft** [comment]
Yea looks harmless

On Mon, May 9, 2016, 23:14 Justin Lewis Salmon notifications@github.com
wrote:

> OK to merge?
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/2#issuecomment-217991987
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by quixoft** [comment]
Whoops sorry about email...

**Pull request merged**
