### PR TITLE
Added usb_io class to supress resetting arduino on reconnect

### PR DESCRIPTION
**Pull request by quixoft**
I hope I did it correctly this time.

### CODE REVIEW

**Comment by juzsal** [comment]
Very nice! Looks good to me.

Does it solve the problem with the breakout boards becoming unreachable too? #16

**Comment by quixoft** [comment]
No, thats another problem I am looking at. They die on me on a reset !!
PS Is it you who does the commit ?

On Sat, May 14, 2016 at 9:02 PM, Justin Lewis Salmon <
notifications@github.com> wrote:

> Very nice! Looks good to me.
> 
> Does it solve the problem with the breakout boards becoming unreachable
> too? #16 https://github.com/CosmicPi/cosmicpi-daq/issues/16
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/17#issuecomment-219237412

## 

Julian Lewis
14, Les Nepliers,
Leaz, 01200, France

+33972343022 (Home France)
+33646447515 (Mobile France Private)

**Comment by juzsal** [comment]
Ok, I'm sure you'll figure that one out. Yeah it's me who does it - I'll merge it now.

**Comment by quixoft** [comment]
Thanks

On Sat, May 14, 2016 at 9:07 PM, Justin Lewis Salmon <
notifications@github.com> wrote:

> Merged #17 https://github.com/CosmicPi/cosmicpi-daq/pull/17.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/17#event-660791786

## 

Julian Lewis
14, Les Nepliers,
Leaz, 01200, France

+33972343022 (Home France)
+33646447515 (Mobile France Private)

**Pull request merged**
