### PR TITLE
Rename packet variables to be human-readable

### PR DESCRIPTION
**Pull request by juzsal**
Sister PR to CosmicPi/cosmicpi-arduino#3

### CODE REVIEW

**Comment by quixoft** [comment]
From looking its OK, I say go for the commit. We will see any problems later when I test it. I need to do some soldering to get my breakouts up an running.

**Comment by juzsal** [comment]
Thanks! I ran it with the firmware and it seemed to work. Let me know how your testing goes.

**Comment by quixoft** [comment]
Can you just commit it all, and I will pull for the tests. Its easy if I
see a bug to fix it later

On Tue, May 10, 2016 at 4:30 PM, Justin Lewis Salmon <
notifications@github.com> wrote:

> Merged #3 https://github.com/CosmicPi/cosmicpi-daq/pull/3.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/3#event-655841904

## 

Julian Lewis
14, Les Nepliers,
Leaz, 01200, France

+33972343022 (Home France)
+33646447515 (Mobile France Private)

**Comment by juzsal** [comment]
Done!

**Comment by quixoft** [comment]
And the arduino mods please

On Tue, May 10, 2016 at 4:37 PM, Justin Lewis Salmon <
notifications@github.com> wrote:

> Done!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/3#issuecomment-218177506

## 

Julian Lewis
14, Les Nepliers,
Leaz, 01200, France

+33972343022 (Home France)
+33646447515 (Mobile France Private)

**Comment by juzsal** [comment]
Sorry, I thought I did that already. Done!

**Comment by quixoft** [comment]
Super thanks

On Tue, May 10, 2016 at 4:39 PM, Justin Lewis Salmon <
notifications@github.com> wrote:

> Sorry, I thought I did that already. Done!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/3#issuecomment-218178093

## 

Julian Lewis
14, Les Nepliers,
Leaz, 01200, France

+33972343022 (Home France)
+33646447515 (Mobile France Private)

**Pull request merged**
