### PR TITLE
Add file-based configuration, restructure into installable package

### PR DESCRIPTION
**Pull request by juzsal**
- Package can now be installed locally via `sudo python setup.py install`
- Can also install remotely via `pip`: 

`sudo pip install https://github.com/jlsalmon/cosmicpi-daq/tarball/master#egg=cosmcipi-0.0.1`
- We could even add it to PyPI, then we could just use `sudo pip install cosmicpi`
- Executables will be installed at `/usr/local/bin/cosmicpi` and `/usr/local/bin/cosmcipi-cli`
- Configuration now possible by YAML file whose contents will override the built-in defaults
- CLI args will override the defaults and those specified in the config file (cascading configuration)

Misc other changes:
- Moved python source files into `cosmicpi/` directory
- Configuration options are now held in a nested dict (e.g. `options.broker["host"]`)
- Changed some CLI arg names and inverted some defaults
- Renamed some classes (Socket_io -> EventPublisher, usb_io -> UsbHandler)
- Renamed cosmicpi-daq.py -> cosmicpi.py

### CODE REVIEW

**Comment by juzsal** [comment]
@quixoft did you manage to take a look at this one? It's kind of big, I know... :)

**Comment by quixoft** [comment]
There are some good ideas there, there are many ways we could achieve the same thing. My only worry is that you are committing to a Linux solution. In principle python runs fine on Windows, and the installation could be simply down loading the source and running it. So if we are definitively dropping Windows and committing to the raspberry pi then ok. But remember we don't even need a pi, any pc running any os with a USB port would do the trick. 

But if we are ok with the implications of your installation, then it's fine. A deb package would also do the trick but be even more restrictive, or a tar ball is one of my preferred method for distributing packages.  

So difficult for me to have a strong opinion .

**Comment by juzsal** [comment]
If you look in `setup.py` you'll see the `entry_points` dict - this will actually also place `.exe` wrappers in the right place on Windows which is pretty cool. But as far as general Windows support goes, I think there are other parts of the program that would need re-working. 

I'm sticking to Linux for now, but I don't think it would be too much effort to support it in the future. We could also easily build a tarball with a bit of hacking of `setup.py`.

**Comment by juzsal** [comment]
Shall I merge this in then? The next one will be some tasty CLI enhancements.

**Comment by quixoft** [comment]
Yeah go for it

**Comment by quixoft** [comment]
Having difficulties, now things are becoming more and more obscure and difficult to diagnose. 
First I do not want stuff installed in /usr/local while I am testing and probably never will, I am trying to debug and am being forced to deal with stuff that is now getting in the way to the point where I am no longer able to diagnose problems correctly. 

For example I have the -n option, why is it trying to contact the broker ?

julian@TTLeaz:~/git-pi/cosmicpi-daq/cosmicpi$ python cosmicpi.py  -n -i devineswiss.no-ip.org -p 8080 -u /dev/ttyACM0
WARN: no config file could be found at /etc/cosmicpi.yaml
INFO: using logging configuration from /home/julian/git-pi/cosmicpi-daq/cosmicpi/logging.conf
[2016-05-24 23:09:28,294]    ERROR [base_connection.py         335] Socket Error: 104
[2016-05-24 23:09:28,294]    ERROR [base_connection.py         335] Socket Error: 104
[2016-05-24 23:09:28,295]    ERROR [base_connection.py         171] Socket closed while authenticating indicating a probable authentication error
[2016-05-24 23:09:28,295]    ERROR [base_connection.py         171] Socket closed while authenticating indicating a probable authentication error
[2016-05-24 23:09:28,295]    ERROR [event_publisher.py          25] Fatal: Couldn't establish a connection to the broker. Please check the connection parameters.
[2016-05-24 23:09:28,295]    ERROR [event_publisher.py          26] Fatal: Connection parameters were: guest:guest@devineswiss.no-ip.org:8080
[2016-05-24 23:09:28,295]    ERROR [cosmicpi.py                 80] Exception: Can't connect to broker

and this 

julian@TTLeaz:~/git-pi/cosmicpi-daq/cosmicpi$ python cosmicpi.py  -n -u /dev/ttyACM0
WARN: no config file could be found at /etc/cosmicpi.yaml
INFO: using logging configuration from /home/julian/git-pi/cosmicpi-daq/cosmicpi/logging.conf
[2016-05-24 23:53:46,706]    ERROR [event_publisher.py          25] Fatal: Couldn't establish a connection to the broker. Please check the connection parameters.
[2016-05-24 23:53:46,706]    ERROR [event_publisher.py          26] Fatal: Connection parameters were: guest:guest@localhost:5162
[2016-05-24 23:53:46,706]    ERROR [cosmicpi.py                 80] Exception: Can't connect to broker

and this

julian@TTLeaz:~/git-pi/cosmicpi-daq/cosmicpi$ python cosmicpi.py  -n -u /dev/ttyACM0 --config logging.conf 
WARN: invalid configuration file at logging.conf: expected '<document start>', but found '<scalar>'
  in "logging.conf", line 2, column 1
INFO: using logging configuration from /home/julian/git-pi/cosmicpi-daq/cosmicpi/logging.conf
[2016-05-24 23:54:39,779]    ERROR [event_publisher.py          25] Fatal: Couldn't establish a connection to the broker. Please check the connection parameters.
[2016-05-24 23:54:39,779]    ERROR [event_publisher.py          26] Fatal: Connection parameters were: guest:guest@localhost:5162
[2016-05-24 23:54:39,779]    ERROR [cosmicpi.py                 80] Exception: Can't connect to broker

And now look at this ... Where is the config file ?

julian@TTLeaz:~/git-pi/cosmicpi-daq/cosmicpi$ python cosmicpi.py -i devineswiss.no-ip.org -p 8080 -u /dev/ttyACM0
WARN: no config file could be found at /etc/cosmicpi.yaml
INFO: using logging configuration from /home/julian/git-pi/cosmicpi-daq/cosmicpi/logging.conf
[2016-05-24 23:16:30,823]    ERROR [base_connection.py         335] Socket Error: 104
[2016-05-24 23:16:30,823]    ERROR [base_connection.py         335] Socket Error: 104
[2016-05-24 23:16:30,823]    ERROR [base_connection.py         171] Socket closed while authenticating indicating a probable authentication error
[2016-05-24 23:16:30,823]    ERROR [base_connection.py         171] Socket closed while authenticating indicating a probable authentication error
[2016-05-24 23:16:30,823]    ERROR [event_publisher.py          25] Fatal: Couldn't establish a connection to the broker. Please check the connection parameters.
[2016-05-24 23:16:30,823]    ERROR [event_publisher.py          26] Fatal: Connection parameters were: guest:guest@devineswiss.no-ip.org:8080
[2016-05-24 23:16:30,823]    ERROR [cosmicpi.py                 80] Exception: Can't connect to broker

So lets try to find something that looks like a config .....

julian@TTLeaz:~/git-pi/cosmicpi-daq/cosmicpi$ python cosmicpi.py  -i devineswiss.no-ip.org -p 8080 -u /dev/ttyACM0 --config logging.conf 
WARN: invalid configuration file at logging.conf: expected '<document start>', but found '<scalar>'
  in "logging.conf", line 2, column 1
INFO: using logging configuration from /home/julian/git-pi/cosmicpi-daq/cosmicpi/logging.conf
[2016-05-24 23:18:37,074]    ERROR [base_connection.py         335] Socket Error: 104
[2016-05-24 23:18:37,074]    ERROR [base_connection.py         335] Socket Error: 104
[2016-05-24 23:18:37,074]    ERROR [base_connection.py         171] Socket closed while authenticating indicating a probable authentication error
[2016-05-24 23:18:37,074]    ERROR [base_connection.py         171] Socket closed while authenticating indicating a probable authentication error
[2016-05-24 23:18:37,074]    ERROR [event_publisher.py          25] Fatal: Couldn't establish a connection to the broker. Please check the connection parameters.
[2016-05-24 23:18:37,075]    ERROR [event_publisher.py          26] Fatal: Connection parameters were: guest:guest@devineswiss.no-ip.org:8080
[2016-05-24 23:18:37,075]    ERROR [cosmicpi.py                 80] Exception: Can't connect to broker

---

Right here are some suggestions

1) Make a run script its getting to complicated "run-daemon"
2) Make a proper README with useful information in it

and the big one

3) Under no circumstances EVER should the daemon just exit with incorrect arguments. There have to be working defaults for all parameters. Most users are not interested in daemon internal error dumps, they are meaningless to them.

4) Any configuration files should be supplied and clearly marked as such, it must be possible to have them local. The first place the daemon should look is in the current directory, then in other places, the usual hierarchical local/global Linux configuration search. If it can't find one it should use defaults that work. IE no broker and try/except logic around the USB port. (I know I didn't do that either, but I should have)

Until such time as we have a working system I find it very inconvenient not to have the system in one place in my home directory. Also after the git fetch merge I see the cosmicpi subdirectory with something called setup.py in the parent. What is that for ? README/script please.

Sorry to be critical, but in my opinion you are adding far too much complexity, too many black boxes and making it more and more difficult to figure out what to do when something goes wrong. This is going to seriously screw things up for the end users and kill their enthusiasm for the project, you are making them dependent on you, don't do it. 
Again thanks for all the hard work, but please keep it simple and easy to use and easy to figure out how to fix it when it breaks.

At the moment I can't get the deamon/cli up and running, maybe the broker is dead, but if it is, then I have just behaved like one of the thousands of eventual end users and you would be getting only one star out of five on the App store. Cheers

**Pull request merged**
