### PR TITLE
Make sure sent packets are valid JSON strings

### PR DESCRIPTION
**Pull request by juzsal**
The event, weather and vibration packets were sent with a `*` character separating them, which isn't valid JSON. This PR fixes that and additionally uses the builtin JSON module to serialise dictionaries.

### CODE REVIEW

**Comment by quixoft** [comment]
Yes that was a cludge I put in so that I could easily split on \* in the server. It was just to join dictionaries together. I am ok with that mod, ok by me to commit

**Comment by quixoft** [comment]
OK I am now sending packets with the new server

./cosmicpi-daq.py -i devineswiss.no-ip.org -p 8080 -u /dev/ttyACM0

options (Server IP address)     ip   : devineswiss.no-ip.org
options (Server Port number)    port : 8080
options (USB device name)       usb  : /dev/ttyACM0
options (Logging directory)     odir : /tmp
options (Event logging)         log  : False
options (UDP sending)           udp  : True
options (Vibration monitor)     vib  : False
options (Weather Station)       wst  : False
options (Cosmic Ray Station)    cray : True
options (Push notifications)    patk : 
options (Debug Flag)            debug: False

cosmic_pi monitor running, hit '>' for commands

cosmic_pi:uptime:55 :queue_size:0 time_string:[11/May/2016 13:52:52] 135258

**Comment by quixoft** [comment]
Here is what happens when I switched the weather on
Fatal: Exception: main: 
Traceback (most recent call last):
  File "./cosmicpi-daq.py", line 541, in main
    sio.send_event_pkt(wbuf)
  File "./cosmicpi-daq.py", line 265, in send_event_pkt
    self.channel.basic_publish(exchange='events', routing_key='', body=json.dumps(pkt))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 2065, in publish
    self._flush_output()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Up time:243 Quitting ...
Traceback (most recent call last):
  File "./cosmicpi-daq.py", line 594, in <module>
    main()
  File "./cosmicpi-daq.py", line 589, in main
    sio.close()
  File "./cosmicpi-daq.py", line 268, in close
    self.connection.close()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 629, in close
    self._flush_output(self._closed_result.is_ready)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed

**Comment by quixoft** [comment]
This is caused when the HTU chip is down, having re-initialized the chip messages get sent. So the error is when no HTU chip messages have ever been sent and you attempt to access then. Badly initialized variable at runtime - the python error I get screwed by most often.

**Comment by quixoft** [comment]
OK its very very clunky, its crashing continuously whenever there is an event stream. The DAQ client is just not robust enough, it looks like when its hit by the DUE emptying its event queue it dies - So it isn't getting past even basic functionality. 
How should we continue now ? I suggest you come over to my home-lab and we do the tests together so as to get to the bottom of the performance issues. (Plenty of beer and coffee available) plus I have a fully configured DUE + test equipment

**Comment by juzsal** [comment]
Again, please don't just randomly reply to unrelated threads, [create an issue](https://github.com/CosmicPi/cosmicpi-daq/issues/new) instead

**Comment by juzsal** [comment]
FYI, CosmicPi/cosmicpi-daq#7 fixes the issue you describe

**Pull request merged**
