### PR TITLE
Publish events to a message broker (RabbitMQ) rather than using UDP

### PR DESCRIPTION
**Pull request by juzsal**
Switch to publishing to a messaging broker rather than using raw UDP packets. This is for a number of reasons:
- Guaranteed delivery of messages
- Do not need to manually implement packet sequence numbering
- Connection management is offloaded to the message broker which is designed to deal with massive numbers of connections with ease
- Client and server are not coupled together - client can still send even when the server is down
- Multiple server applications can consume the same streams of data - the client only needs to know a single publication address
- Allows consumers to use an event-based model rather than having to poll for updates

### CODE REVIEW

**Comment by quixoft** [comment]
As it is you who will be responsible for maintaining this then you should go your own way. I could argue every one of the points in your bulleted list. But in the end both transport methods have their pros and cons. So I am not going to object, but in my opinion it might be advisable to discuss more before getting into bed with sonicmq, there are other moms around.

**Comment by juzsal** [comment]
Another point is the amount of code that you have to write around a particular transport mechanism to get a robust piece of software. Using an extremely well-tested, off-the-shelf product such as RabbitMQ (not sonicmq ;) means you only need a few lines and you know that you don't need to worry at all about the transport.

Using raw UDP (or even raw TCP sockets) requires a lot of surrounding code for error checking, robustness etc. And even if you do write that code, it will not be as good as what somebody else has already written.

I do not like reinventing the wheel. Worse still, I do not like _poorly_ reinventing the wheel.

I also do not like maintaining code that I don't have to, when I can profit from somebody else's years of experience and development.

**Comment by quixoft** [comment]
Hmm, some innuendos in that. I wasn't suggesting using raw Ethernet, nor re implementing Udp. The entire data transmission was 10 lines of python. So it makes use of lots of stuff written by other people with lots of experience.  Nor is using Udp reinventing wheels, it's a common light connectionless transport that is simple and reliable.

**Comment by quixoft** [comment]
https://www.rabbitmq.com/mpl.html

Is this an issue ?

**Comment by juzsal** [comment]
It may be only 10 lines, but it's not quite complete how it is right now. What about these things:
- Message acknowledgements 
- Retransmission of unacknowledged messages
- Queueing of messages if the server is unreachable
- Messages received out-of-order

That is all code that would need to be written around  the current UDP-based system. Code that has already been written many, many times by other people, a lot better than we could do it.

Why do that when you can get it all for free, open-source and battle-tested?

P.S. I didn't mean to insinuate anything - I'm just being pragmatic, this is a free-time project for me and I need to get the most value out of the least time, code and effort as I can.

**Comment by quixoft** [comment]
Well yet another bulleted list, so 1) what are you going to do with no connection to the broker ? You still need to store packets until the connection comes back up. Some places may have very sporadic internet availability. 2) same problem 3) same problem 4) sequence numbers, and any way it doesn't matter as long as they get there.

**Comment by juzsal** [comment]
What am I going to do with no connection to the broker? I am going to put another broker on the Pi that handles everything for me. Another piece of software that I didn't write and don't have to maintain. https://www.rabbitmq.com/distributed.html

**Comment by quixoft** [comment]
From a raspberry pi all by itself at the North pole ?

**Comment by juzsal** [comment]
Yes, why not? If there's no internet, it will store packets until the disk is full, then FIFO.

**Comment by quixoft** [comment]
Well then to solve the problem of no internet you store messages on the disc via a local broker... Then when the connection comes back it sends them all to the server via a remote broker. So if I understand correctly you need to implement a broker on the pi, specify the behavior in some configuration file. Otherwise with udp you just send the packets and store them, every now and  you ask if any are missing, and throw them away if it's ok. In both cases you need to handle network failures. So there is work to be done either way. In the Udp case the code is trivial, a few lines of python. What you are suggesting isn't remotely simpler... Any way, let's just agree to differ on this one. You are in charge so you should do what you want, if it was me, I would do it with udp and python.

**Comment by quixoft** [comment]
By the way is the licence ok for us to distribute in our code, it looks a bit wired

**Comment by quixoft** [comment]
Oh I almost forgot, I have a working client at my house, I can seen packets, with whatever transport you want to help you test from multiple sources. If you have a server up and running let me know if it would be useful for tests

**Comment by quixoft** [comment]
Intact it would be very useful for me to go through the rabbit mq installation and set up to actually send some packets to a real server. Then we could see how well it works, so do your commit and I will pull it

**Comment by juzsal** [comment]
The broker is running on James' server on port 8080. Just point your DAQ to it with `--host` and `--port`. You'll need to install `pika` but nothing else.

The MPL looks to be compatible with GPLv2+

**Comment by quixoft** [comment]
Good I will do that

**Pull request merged**
