### PR TITLE
Add an option to simulate events without serial access

### PR DESCRIPTION
**Pull request by juzsal**
This is useful for testing and if the Arduino isn't available for some reason.

### CODE REVIEW

**Comment by quixoft** [comment]
Good, the events you simulate are all zero, I guess you just want to test
the connection. I think it might be interesting to add a field on the
status saying simulated so that they are thrown away. Imagine what might
happen if every one started simulating events...perhaps the server can be
modified to recognise zero events and throw them away. In any case there is
an impression on the server

On Mon, May 9, 2016, 21:45 Justin Lewis Salmon notifications@github.com
wrote:

> This is useful for testing and if the Arduino isn't available for some
> 
> ## reason.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/CosmicPi/cosmicpi-daq/pull/1
> Commit Summary
> - Added a simulation option
> 
> File Changes
> - _M_ cosmicpi-daq.py
>   https://github.com/CosmicPi/cosmicpi-daq/pull/1/files#diff-0 (12)
> 
> Patch Links:
> - https://github.com/CosmicPi/cosmicpi-daq/pull/1.patch
> - https://github.com/CosmicPi/cosmicpi-daq/pull/1.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/1
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
@quixoft what do you think?

**Comment by juzsal** [comment]
This was more-or-less just a dummy commit to demonstrate the workflow.

You're right, there should be a simulated flag. I eventually would like to simulate all the types of packets with real-looking values to test the whole chain, and yes those packets should be discarded.

If this looks good to you, I'll merge it.

**Comment by quixoft** [comment]
It's good but incomplete, so if you want to do the simulation described I
would ask why ? There is network testing, then simply throwing away zero
events at the server is ok. If you are really trying to simulate real data
then that is a can of worms. An interesting can of worms, but a massive
problem. So if you want to merge you should first patch the server to throw
away zeros, that's a minor mod.

On Mon, May 9, 2016, 22:00 Justin Lewis Salmon notifications@github.com
wrote:

> This was more-or-less just a dummy commit to demonstrate the workflow.
> 
> You're right, there should be a simulated flag. I eventually would like to
> simulate all the types of packets with real-looking values to test the
> whole chain, and yes those packets should be discarded.
> 
> If this looks good to you, I'll merge it.
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/pull/1#issuecomment-217972245
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
I'll close this since it was just a demo and wasn't really a fully thought-out idea.

**Pull request closed without merging**
